const $=s=>document.querySelector(s);let catalog;
const descriptions={platformer:'已有关卡、角色二段跳、14 枚金币、下坠平台和顶碎砖块。旗帜目前只用于装饰。','city-builder':'自动加载官方示例小镇：122 个格子、15 种结构、余额 5860。具备单格建造与基础存读档。',racing:'黄色卡车、拼块赛道、森林与帐篷。附带可接入的摩托车；尚无计时和检查点玩法。'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function link(label,path){const a=el('a',label);a.href=path;return a;}
function list(parent,title,items){parent.append(el('h4',title));const ul=el('ul');for(const x of items)ul.append(el('li',x));parent.append(ul);}
async function play(id){$('#status').textContent='正在打开初始场景…';try{const r=await fetch('/api/play',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:id})});if(!r.ok)throw new Error('启动失败，请检查服务日志');const j=await r.json();$('#status').textContent=j.message;}catch(e){$('#status').textContent=e.message;}}
function draw(filter='all'){$('#tasks').replaceChildren();for(const t of catalog.tasks.filter(t=>filter==='all'||t.base_id===filter)){const card=el('article',undefined,'task');const meta=el('div',undefined,'meta');meta.append(el('span',t.id),el('span',t.category),el('span',t.difficulty==='hard'?'较难':'中等'));card.append(meta,el('h3',t.title),el('p',t.query));const details=el('details');details.append(el('summary','初始状态、素材与任务范围'));details.append(el('h4','初始状态'));const state=el('pre',typeof t.initial_state==='string'?t.initial_state:JSON.stringify(t.initial_state,null,2));details.append(state);list(details,'可用素材与代码资源',t.available_assets);list(details,'允许修改范围',t.editable_paths);list(details,'需要保留',t.required_preservation);list(details,'审阅要点（未实现自动校验器）',t.acceptance_notes);details.append(el('h4','复制为独立工作目录'),el('pre',`python3 tools/inputs.py prepare ${t.id} --dest /absolute/path/to/new-workspace`));card.append(details,link('完整需求 ↗',`tasks/${t.id}/QUERY.md`),document.createTextNode('　'),link('输入 JSON ↗',`tasks/${t.id}/task.json`));$('#tasks').append(card);}}
async function load(){try{catalog=await(await fetch('catalog.json')).json();for(const b of catalog.bases){const card=el('article',undefined,'base');const img=el('img');img.src=b.preview;img.alt=b.name+'在本机运行的初始场景';const body=el('div',undefined,'pad');body.append(el('h3',b.name),el('p',descriptions[b.id]));const btn=el('button','打开初始场景 ↗','play');btn.onclick=()=>play(catalog.tasks.find(t=>t.base_id===b.id).id);body.append(btn);const links=el('div',undefined,'base-links');links.append(link('工程说明',b.readme),link('来源与许可证',b.source));body.append(links);card.append(img,body);$('#bases').append(card);}draw();}catch(e){$('#status').textContent='目录加载失败：'+e.message;}}
$('#filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$('#filters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.filter);});load();
